In [3]:
# inference of nn
# h = xW + b
# mini-batch version nn
import numpy as np
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.dot(x, W1) + b1
print(W1)
print(b1)
print(np.dot(x, W1))
print(h)

[[ 0.62461377  1.2144206   0.2659123  -0.13177798]
 [-0.9952449  -0.61325293  0.0383907  -0.3697716 ]]
[-0.95479794  0.7789426  -0.58961902 -0.90648772]
[[-2.16198273 -2.59835266 -0.35925473 -0.24790277]
 [-1.0472482  -1.54779084 -0.27511269  0.00674971]
 [-0.5320618  -0.05160915  0.1170959  -0.31884204]
 [-1.75791633 -1.50856527 -0.08089703 -0.46656318]
 [-2.91805913 -2.33877767 -0.07647233 -0.8470061 ]
 [-0.91303675 -0.95934712 -0.10348284 -0.16521008]
 [ 2.11740588  1.69120199  0.05343959  0.61717809]
 [-1.71927246 -1.61392622 -0.12754606 -0.39554917]
 [-0.99518113 -0.21125412  0.17891211 -0.54605114]
 [ 2.73745885  3.14234061  0.4032662   0.37864622]]
[[-3.11678067 -1.81941006 -0.94887374 -1.15439048]
 [-2.00204614 -0.76884824 -0.8647317  -0.89973801]
 [-1.48685974  0.72733345 -0.47252312 -1.22532976]
 [-2.71271427 -0.72962267 -0.67051605 -1.3730509 ]
 [-3.87285707 -1.55983507 -0.66609134 -1.75349382]
 [-1.86783469 -0.18040452 -0.69310186 -1.0716978 ]
 [ 1.16260794  2.47014459 -0.5

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [7]:
a = sigmoid(h)
a

array([[0.04242035, 0.13950468, 0.27911138, 0.23968806],
       [0.11898826, 0.31672831, 0.29635171, 0.28910434],
       [0.18439353, 0.67421984, 0.38401923, 0.22699987],
       [0.06222727, 0.32527754, 0.3383813 , 0.20212738],
       [0.02037508, 0.17367031, 0.33937261, 0.14760707],
       [0.13379247, 0.45502079, 0.3333434 , 0.25508034],
       [0.76180627, 0.92202216, 0.36907679, 0.42817289],
       [0.06452085, 0.30259234, 0.32801756, 0.21382241],
       [0.12455564, 0.63822963, 0.39874263, 0.18961114],
       [0.85602512, 0.98056938, 0.45354615, 0.37102047]])

In [10]:
# add the sigmoid layer
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)
x = np.random.randn(10, 2) # 2 features
h = np.dot(x, W1) + b1
a = sigmoid(h)
s = np.dot(a, W2) + b2  # 3 classes (10, 3) 
print(x.shape, W1.shape, h.shape, W2.shape, s.shape)

(10, 2) (2, 4) (10, 4) (4, 3) (10, 3)


Create the nn with class:

Affine -> Sigmoid -> Affine

In [13]:
# create class for layer sigmoid
import numpy as np

class Sigmoid():
    
    def __init__(self):
        self.params = []  # have no params for learning
        
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [12]:
# Affine layer (全联接层)
class Affine:

    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

In [14]:
# Two layer net
# Affine -> Sigmoid -> Affine
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        # init weight and bias
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # create layer
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # add all the weights to the params list
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [15]:
# inference with the nn
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
s

array([[ 1.68844636,  0.39330731,  3.05041955],
       [ 1.84456739,  0.17384794,  1.71543507],
       [ 1.85803044,  0.38345414,  1.82811933],
       [ 1.6901803 ,  0.62057506,  2.80134375],
       [ 1.72725251,  0.04285055,  2.69147908],
       [ 1.8998701 ,  0.15892358,  1.5272931 ],
       [ 1.64426747,  0.92152412,  2.68959026],
       [ 1.73940639, -0.27167269,  0.9539565 ],
       [ 1.77428358,  0.11882549,  2.29472944],
       [ 1.8055458 ,  0.39715877,  2.08358442]])

beautiful! Next, how dose nn train?

net:

X -> Affine -> Sigmoid -> Affine -> **Softmax with Loss layer**（Softmax -> CrossEntropyError -> Loss Function）

* 损失函数：Softmax本质是概率，和为1，Softmax将计算结果和正确标签的one-hot形式一起传递给交叉熵函数，计算出该batch的损失
* 导数和梯度：梯度向量，其实就是对W矩阵的各个元素求偏导后的矩阵
* 链式法则，复合函数不断求导，进行反向传播
* sigmoid求偏导：y(1 - y)*上一层传过来的梯度dout

In [18]:
# add backward to sigmoid class
class Sigmoid():
    
    def __init__(self):
        self.params, self.grads = [], []
        self.out = None
        
    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx

In [1]:
# the backward of matmul point class (矩阵乘积节点的类)
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zero_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.dot(x, W)
        self.x = x
        return out

    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grad[0][...] = dW
        return dx

a=b和a[...]=b的区别是使用省略号时数据被覆盖，变量指向的内存地址不变

In [2]:
class SGD:
    def __init__(self, lr=0.01):
        self.lr = lr
    def update(self, params, grads):
        for i in range(len(params)):
            params[i] -= self.lr * grads[i]

### 关于神经网络的思考

对于神经网络的经典的那张图。就是类似于神经元连接的图。虽然通过代码敲了几次但是其实还是没有完全理解，直到再次学习矩阵点积运算，想到其实是特征向量和权重向量进行运算的不断迭代，每次的新的一排输出的原点就是新的特征提取向量。最终进行一个扁平运算然后输出最终的结果，其实这个最终的结果也是一种特征提取，给每一个最终特征一个概率，就可以通过argmax得到最后的分类结果。

通过卷积神经网络的过程也可以理解到，整个深度学习的过程，其实就是不断提取数据特征的过程。

正因为如此，我们在一开始的数据处理就显得特别重要，因为初始化的特征向量就是一开始的重要基准，对特征进行标准化，有助于后期更好的进行特征提取。