### tensors

In [1]:
import torch
# scaler
scaler = torch.tensor(7)
print(scaler)

# get tensor back as python int
scaler.item()

tensor(7)


7

In [2]:
# if vector
# Vector
vector = torch.tensor([7, 7])
print(vector)

# Get tensor back as Python int
for item in vector:
    print(item.item())

tensor([7, 7])
7
7


In [7]:
x = torch.tensor([10, 7])
# squeezing : remove all 1 dimension from tensor
x.squeeze()
# unsqueezing : add a 1 dimension to tensor
x.unsqueeze(dim=1)
print(x)
# permute : swap dimension of a tensor
x = torch.rand(size=(224, 224, 3))
torch.permute(x, (2, 0, 1)).size()

tensor([10,  7])


torch.Size([3, 224, 224])

In [4]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x.shape

torch.Size([1, 3, 3])

In [11]:
import numpy as np
# numpy array to tensor, default data type is float64 because of reflact by numpy 
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
# tensor to numpy array
m = torch.Tensor.numpy(tensor)
m

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

### model architecture

In [ ]:
from torch import nn

# create linear regression model class
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
        self.bias = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
    
    # forward method to define the computation in the model
    def forward(self, x: torch.Tensor):
        return self.weight * x + self.bias

In [ ]:
model = LinearRegressionModel()

# make predictions with inference mode
with torch.inference_mode():
    y_preds = model(X_test)

y_preds