### tensor

In [1]:
# user tensorflow installed env

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# create tensor
scalar = tf.constant(7)
scalar

In [ ]:
# number of dimensions
scalar.ndim

In [ ]:
# create a vector
vector = tf.constant([10, 10])
vector

In [ ]:
vector.ndim

In [37]:
# create a matrix
matrix = tf.constant([[10, 7, 6], [1, 7, 10]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  6],
       [ 1,  7, 10]], dtype=int32)>

In [38]:
matrix.ndim

2

In [ ]:
# another matrix
another_matrix = tf.constant([[10., 7.], [12., 7.], [1., 6.]], dtype = tf.float16)
another_matrix

In [ ]:
another_matrix.ndim

In [ ]:
tensor.ndim  # tensor实质是一个n维数组

### tf.variable

In [2]:
# create tensor with tf.variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor,  unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [4]:
# change value with .assign()
changeable_tensor[0].assign(7)
changeable_tensor
# unchangeable_tensor can not be change

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

大部分时候适用constant就好了，当需要改变的时候重新创建就好

In [139]:
changeable_tensor.assign([3, 4])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>

In [141]:
changeable_tensor.assign_add([10, 10])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([13, 14], dtype=int32)>

### random tensor

In [6]:
# create random tensor
random_g = tf.random.Generator.from_seed(42) # This is a random num generator
random_1 = random_g.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### shuffle

In [7]:
# shuffle the order of elements in a tensor
no_shuffled = tf.constant([
    [10, 7],
    [3, 40],
    [23, 9]
])
no_shuffled.ndim 

2

In [28]:
tf.random.set_seed(42) # global seed
tf.random.shuffle(no_shuffled, seed=42) # operation level random seed
# no_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3, 40],
       [23,  9]], dtype=int32)>

两个seed都需要使用来固定顺序

### Numpy to tensors

In [29]:
# create tensor with ones, zeros
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [30]:
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [31]:
tf.zeros(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [32]:
# turn numpy array into tensor
# tensor vs numpy arrays difference: can be run on gpu and very fast
import numpy as np
numpy_a = np.arange(1, 25, dtype=np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [33]:
A = tf.constant(numpy_a)
B = tf.constant(numpy_a, shape=(2, 3, 4))
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [34]:
B.ndim

3

### tensor attributes (getting info from tensor)
* shape:  tensor.shape
* rank:   tensor.ndim
* axis or dimession:  slice a tensor
* size: tf.size(tensor)

In [40]:
# create a rank 4 tensor
rank_4_tensor = tf.ones(shape=(2, 1, 3, 2))
rank_4_tensor

<tf.Tensor: shape=(2, 1, 3, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]]]], dtype=float32)>

In [41]:
rank_4_tensor.ndim

4

In [42]:
rank_4_tensor[0]

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

In [48]:
rank_4_tensor.shape
# rank_4_tensor.shape[0]  # 2

TensorShape([2, 1, 3, 2])

In [52]:
tf.size(rank_4_tensor)
tf.size(rank_4_tensor).numpy()

12

In [45]:
rank_4_tensor.dtype

tf.float32

### index & expand

In [53]:
rank_4_tensor[:2, :1, :2, :]

<tf.Tensor: shape=(2, 1, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [61]:
# get the first element from every dimension except the final dimension
rank_4_tensor[0, 0, 0, :]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [62]:
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[1., 1.]]]], dtype=float32)>

In [55]:
rank_4_tensor

<tf.Tensor: shape=(2, 1, 3, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]]]], dtype=float32)>

In [64]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [65]:
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [66]:
# newaxis
# tf.expand_dims
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the last dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [68]:
tf.expand_dims(rank_2_tensor, axis=0) # 0 means expand the 0-axis dimension

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### tensor operations
* matmul
* reshape
* transpose
* tensordot

In [69]:
# python basic operations
tensor1 = tf.constant([[10, 7], [3, 4]])
tensor1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [70]:
tf.multiply(tensor1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [71]:
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [72]:
# matrix dot operations
tf.matmul(tensor1, tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [73]:
tensor1 @ tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [86]:
# create two (2, 3) tensor
tensor2 = tf.constant([[10, 7, 8],
                        [2, 3, 6]])
tensor3 = tf.constant([[10, 1, 8],
                        [0, 5, 6]])

In [84]:
tensor2 @ tensor3  # will cause error

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[171,  83],
       [ 71,  51]], dtype=int32)>

In [87]:
# reshape
tensor3 = tf.reshape(tensor3, shape=(3, 2))

In [88]:
tensor3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  1],
       [ 8,  0],
       [ 5,  6]], dtype=int32)>

In [83]:
# tanspose
tensor3 = tf.transpose(tensor3)

In [85]:
tensor3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  0],
       [ 1,  5],
       [ 8,  6]], dtype=int32)>

In [89]:
# notice reshape and transpose are different!!!

This can be explained by the default behaviour of each method:

* tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
* tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.

In [94]:
tf.tensordot(tensor3, tensor2, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[102,  73,  86],
       [ 80,  56,  64],
       [ 62,  53,  76]], dtype=int32)>

In [92]:
tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  8],
       [ 2,  3,  6]], dtype=int32)>

In [93]:
tensor3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  1],
       [ 8,  0],
       [ 5,  6]], dtype=int32)>

### change data type
tf.cast()

In [96]:
tensor_int = tf.constant([10, 7])
tensor_float = tf.constant([10.1, 7.1])
tensor_int, tensor_float

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.1,  7.1], dtype=float32)>)

In [98]:
tf.cast(tensor_int, dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>

In [101]:
new = tf.cast(tensor_float, dtype=tf.int32)

In [100]:
tensor_float

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.1,  7.1], dtype=float32)>

In [102]:
new

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

### get the absolute value
tf.abs()

In [103]:
tensor_ = tf.constant([-10, -7])

In [104]:
tf.abs(tensor_)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

### find min, max, mean, sum
* from tf.math.reduce_xxx()
* tf.reduce_min()
* tf.reduce_max()
* tf.reduce_mean()
* tf.reduce_sum()
* tf.reduce_std()
* tf.reduce_variance()

In [105]:
random_tensor = tf.constant(np.random.randint(0, 100, 50))

In [106]:
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([52, 55, 69, 40, 89, 94, 85,  6, 95, 19, 94, 61, 94, 68, 55, 58, 45,
       98, 80, 25, 32, 68, 73, 78, 28, 24, 97, 14, 47, 51, 27, 91, 40, 95,
       70, 19, 90, 87, 67, 55, 42, 73, 78, 42, 38,  0, 34, 86, 57, 46])>

In [107]:
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [108]:
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [109]:
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=58>

In [110]:
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2931>

In [116]:
random_tensor = tf.cast(random_tensor, dtype=tf.float32)  # because int is not work to std
tf.math.reduce_std(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=26.81633>

### find the max, min index
* tf.argmax()
* tf.argmin()

In [117]:
random_tensor = tf.constant(np.random.random(50))

In [118]:
tf.argmax(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [119]:
tf.argmin(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [120]:
random_tensor

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.99433939, 0.46798262, 0.56385065, 0.42093954, 0.0960791 ,
       0.36561938, 0.15127308, 0.99405325, 0.54951177, 0.60874238,
       0.64866918, 0.42343701, 0.99160359, 0.92339033, 0.02854912,
       0.68536135, 0.75026027, 0.16364865, 0.25199088, 0.7234455 ,
       0.4738062 , 0.21511352, 0.52121858, 0.25727528, 0.71211302,
       0.24708778, 0.52665457, 0.55816951, 0.58391553, 0.64099157,
       0.24714591, 0.09963376, 0.33819233, 0.76812369, 0.93371074,
       0.00140184, 0.99720311, 0.68051155, 0.98840578, 0.23203409,
       0.72252426, 0.1721251 , 0.65458933, 0.9795604 , 0.74025807,
       0.75056962, 0.60818075, 0.80601582, 0.3240222 , 0.03712957])>

In [121]:
tf.reduce_max(random_tensor), tf.reduce_min(random_tensor)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.9972031148053582>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.0014018436427726266>)

### squeeze a tensor (remove all 1 dimensions)
* tf.squeeze()

In [123]:
random_tensor = tf.constant(np.random.random(50), shape=(1, 1, 1, 1, 50))
random_tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float64, numpy=
array([[[[[0.46662083, 0.74485828, 0.19484158, 0.86228505, 0.26865369,
           0.56624874, 0.00252844, 0.78395048, 0.50343137, 0.45197186,
           0.69273832, 0.44685618, 0.00610448, 0.49369957, 0.73922951,
           0.99390168, 0.52029985, 0.63548457, 0.19725428, 0.74087717,
           0.79743011, 0.82955856, 0.91661717, 0.62800892, 0.19592114,
           0.23397409, 0.48875095, 0.23492552, 0.49789256, 0.00595176,
           0.02088629, 0.71065363, 0.16207963, 0.41368192, 0.89980507,
           0.37926038, 0.36207171, 0.10642786, 0.58919348, 0.91766644,
           0.78801996, 0.77334086, 0.63897667, 0.88725268, 0.65493875,
           0.24888088, 0.77544552, 0.91854825, 0.68020752, 0.60521488]]]]])>

In [124]:
squee_tensor = tf.squeeze(random_tensor)
squee_tensor

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.46662083, 0.74485828, 0.19484158, 0.86228505, 0.26865369,
       0.56624874, 0.00252844, 0.78395048, 0.50343137, 0.45197186,
       0.69273832, 0.44685618, 0.00610448, 0.49369957, 0.73922951,
       0.99390168, 0.52029985, 0.63548457, 0.19725428, 0.74087717,
       0.79743011, 0.82955856, 0.91661717, 0.62800892, 0.19592114,
       0.23397409, 0.48875095, 0.23492552, 0.49789256, 0.00595176,
       0.02088629, 0.71065363, 0.16207963, 0.41368192, 0.89980507,
       0.37926038, 0.36207171, 0.10642786, 0.58919348, 0.91766644,
       0.78801996, 0.77334086, 0.63897667, 0.88725268, 0.65493875,
       0.24888088, 0.77544552, 0.91854825, 0.68020752, 0.60521488])>

### one hot encoder
tf.one_hot(depth, on_value, off_value) 

In [130]:
somelist = [1, 2, 4]
tensor = tf.one_hot(somelist, depth=5, on_value='hello', off_value='--')
tensor

<tf.Tensor: shape=(3, 5), dtype=string, numpy=
array([[b'--', b'hello', b'--', b'--', b'--'],
       [b'--', b'--', b'hello', b'--', b'--'],
       [b'--', b'--', b'--', b'--', b'hello']], dtype=object)>

### Squaring, log, square root
* tf.square() - get the square of every value in a tensor.
* tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
* tf.math.log() - get the natural log of every value in a tensor (elements need to floats).

In [131]:
tensor = tf.constant(np.arange(1, 10))
tensor

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [132]:
tf.square(tensor)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [135]:
tensor2 = tf.cast(tensor, dtype=tf.float32)
tf.sqrt(tensor2)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [137]:
tf.math.log(tensor2)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### tensor to numpy
* np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).
* tensor.numpy() - call on a tensor to convert to an ndarray.

In [142]:
tensor = tf.constant([10, 7])
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [143]:
np.array(tensor)

array([10,  7], dtype=int32)

In [144]:
tensor.numpy()

array([10,  7], dtype=int32)

### use @tf.function can speed up

In [150]:
@tf.function
def function(x, y):
    return x ** 2 + y

x = tf.constant(np.arange(5, 10))
y = tf.constant(np.arange(10, 15))
function(x, y)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([35, 47, 61, 77, 95])>

### finding access to gpus
check if you've got access to a GPU using tf.config.list_physical_devices()

In [154]:
print(tf.config.list_physical_devices('CPU'))

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [152]:
# find information about your GPU using !nvidia-smi
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [155]:
# seems i don't have gpu to use